meta_product_name: "Smart Calendar"
meta_title: "Smart Calendar: Orgnise Your Life"
meta_description: "Smart Calendar, manage your time, change your life!"
meta_image: "app/assets/images/smart_calendar_smalltext.png" # should exist in `app/assets/images/`
twitter_account: "@CalendarSmart"   # required for Twitter Cards
