meta_product_name: "Smart Calendar"
meta_title: "Smart Calendar - Orgnise Your Life"
meta_description: "Smart Calendar, manage your time, change your life!"
meta_image: "https://res.cloudinary.com/dkqexvvb4/image/upload/v1598866312/21skb2ohbpxkkhphdlggbuyhp1lo.png" # should exist in `app/assets/images/`
twitter_account: "@CalendarSmart"   # required for Twitter Cards
